// Design-system adoption audit. Scores each page/component .tsx for kit usage,
// hardcoded hex colors, and raw (un-kit) dialogs. Writes docs/design-rollout-progress.md.
import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, relative } from 'path';

const ROOT = 'src';
const files = [];
(function walk(d) {
  for (const e of readdirSync(d)) {
    const p = join(d, e);
    const s = statSync(p);
    if (s.isDirectory()) walk(p);
    else if (e.endsWith('.tsx') && !p.includes('/ui/') && !p.includes('/kit/')) files.push(p);
  }
})(ROOT);

const rows = files.map((f) => {
  const src = readFileSync(f, 'utf8');
  const usesKit = /@\/components\/kit/.test(src);
  const hex = (src.match(/#[0-9A-Fa-f]{6}\b/g) || []).filter((h) => !['#ffffff', '#000000'].includes(h.toLowerCase()));
  const rawDialog = /<Dialog\b|<Sheet\b|<AlertDialog\b/.test(src);
  const isPage = /\/pages\//.test(f);
  const done = isPage ? (usesKit && hex.length === 0) : (hex.length === 0);
  return { f: relative(ROOT, f), isPage, usesKit, hex: hex.length, rawDialog, done };
});

const areas = {};
for (const r of rows) {
  const parts = r.f.split('/');
  const a = parts[0] === 'pages' ? (parts[2] || parts[1]) : parts[0];
  areas[a] = areas[a] || { total: 0, done: 0, hex: 0, rawDialog: 0 };
  areas[a].total++; if (r.done) areas[a].done++; if (r.hex) areas[a].hex++; if (r.rawDialog) areas[a].rawDialog++;
}

let md = `# Design rollout — progress (auto-generated by scripts/ds-audit.mjs)\n\n`;
md += `Total files: ${rows.length} · adopting kit: ${rows.filter((r) => r.usesKit).length} · with brand-hex: ${rows.filter((r) => r.hex).length} · raw dialogs: ${rows.filter((r) => r.rawDialog).length}\n\n`;
md += `## By area\n\n| area | files | done | brand-hex files | raw-dialog files |\n|--|--|--|--|--|\n`;
for (const [a, v] of Object.entries(areas).sort((x, y) => y[1].total - x[1].total)) {
  md += `| ${a} | ${v.total} | ${v.done} | ${v.hex} | ${v.rawDialog} |\n`;
}
md += `\n## Files still using hardcoded brand hex (convert to \`primary\` token)\n\n`;
for (const r of rows.filter((r) => r.hex).sort((a, b) => b.hex - a.hex).slice(0, 80)) md += `- \`${r.f}\` (${r.hex})\n`;
writeFileSync('docs/design-rollout-progress.md', md);
console.log(`Audited ${rows.length} files → docs/design-rollout-progress.md`);
console.log(`adopting kit: ${rows.filter((r) => r.usesKit).length} | brand-hex files: ${rows.filter((r) => r.hex).length} | raw dialogs: ${rows.filter((r) => r.rawDialog).length}`);
